# Project information
site_name: VIVA workshop
site_url: https://
site_description: viva+  documentation
site_author: VIVA+ Team

# Repository
repo_name: openvt/
repo_url: 

# Copyright
copyright: Copyright &copy; 2019-2020 VIVA+ team

# Page tree
nav:
    - VIVA Workshop: 
        - Outline: index.md
    - Before the workshop:
        - Setup: setup.md
        - Online workshops: online.md
    - Introduction to :
        - Introduction to the Models: 'model-doc/00-model-info.md'
    - Contributor Guide:
        - 'How to Contribute': 'contributor-guide/00-contribute-to-VIVA.md'

# Configuration
theme:
    name: 'material'
    palette:
        primary: 'amber'
        accent: 'teal'
    features:
      - tabs
    icon: #'images/VIRTUAL.png'
        #logo: fontawesome/brands/git-alt
        logo: fontawesome/solid/walking
        repo: fontawesome/brands/git-alt
        # Find more at https://material.io/resources/icons/
    favicon: 'images/favicon.ico'

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - bibtex:
      bib_file: "viva-refs.bib"
#          - "viva-refs-1.bib"
      cite_style: "pandoc"
#  - mknotebooks # pip install mknotebooks

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
