# Project information
site_name: VIVA+ Workshop
site_url: https://viva-workshop.readthedocs.io
site_description: Handouts for VIVA+ Hands-on Workshop
site_author: Jobin John, Corina Klug, Martin Schachner

# Repository
#repo_name: openvt/
#repo_url: 

# Copyright
copyright: Copyright &copy; 2020 VIVA+

# Page tree
nav:
    - Welcome: index.md
    - Pre-workshop Setup :
        - Git Setup: 0-1-setup.md
        - Jupyter Notebook Setup: 0-2-jupyter-notebook-setup.md
        - Practical information: 0-3-online-workshop-info.md

    - VIVA+ Models:
        - Introduction to VIVA+: 1-1-vivaplus-intro.md
        - Model data structure: 1-2-vivaplus-data-structure.md
        - VIVA+ documentation: 1-3-vivaplus-documentation.md
    - Git:
        - Overview: 2-1-git-overview.md
        - Getting started: 2-2-git-intro.md
        - Basic Git Workflow on Local Repo: 2-3-git-basic-workflow.md
        - Working with Remote Repo: 2-4-git-remote-repo.md
    - VIVA+ Postprocessing:
        - Overview: 3-0-postprocessing-overview.md
        - Jupyter: 3-1-postprocess-jupyter-intro.md
        - Dynasaur: 3-2-postprocess-dynasuar.md

#theme: readthedocs
theme:
    name: 'material'
    palette:
        scheme: default
        primary: black
        accent: deep orange
    font:
        text: Open Sans
        #text: Cambay
        #text: Inder
        #text: Voces
        #text: Overlock
        code: Fira Mono
    icon:
        logo: material/library
        
# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true


extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - css/extra.css