# Project information
site_name: VIVA workshop
site_url: https://
site_description: viva+  documentation
site_author: VIVA+ Team

# Repository
repo_name: openvt/
repo_url: 

# Copyright
copyright: Copyright &copy; 2019-2020 VIVA+ team

# Page tree
nav:
    - VIVA Workshop: 
        - Outline: index.md
    - Before the workshop:
        - Setup: setup.md
        - Online workshops: online.md
    - Git:
        - Installation: git-installation.md
        - Introduction to Git: git-intro.md
        - Git Workflow: git-workflow.md
    - VIVA+ Postprocessing:
        - Jupyter: jupyter-intro.md
        - Dynasaur: dynasuar.md

#theme: readthedocs
theme:
    name: 'material'
    palette:
        primary: 'amber'
        accent: 'teal'
# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true


extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
